### ISSUE TITLE
Template Denoising

### ISSUE THREAD

**Issue by xiaolang01** [kongds/Prompt-BERT#11]
![image](https://user-images.githubusercontent.com/44439592/175857590-69d1c894-4f1d-41b3-b62a-66112453bae4.png)
The Template Denoising in the paper I understand is the first method. Have you tried the second noise reduction method?

**Comment by kongds** [comment]
Hello, 
I have not tried the second method. 
Because I think that replacing sentences with mask will affect the representation of the template.  (Maybe [PAD] is better)

But I'm not sure.

**Comment by xiaolang01** [comment]
I got it, thanks, I didn't find the part about OptiPrompt in your code, where can I find this part

**Comment by kongds** [comment]
OptiPrompt can been reproduced with `./run.sh bert-optiprompt` with the flags `mask_embedding_sentence_autoprompt`. You can find correspond code in models.py.
It first freeze bert in model.py:395 and use input_embeds as BERT input to make template embedding update by grad.

**Comment by xiaolang01** [comment]
ok, thanks for your patience

**Comment by kongds** [comment]
You're welcome.
