### ISSUE TITLE
A question about the paper

### ISSUE THREAD

**Issue by Aureole-1210** [kongds/Prompt-BERT#12]
Hello, I have just read the excellent paper. And I have a question. I want to know if the "frequency" in Figure1 is calculated from the datasets where 「5.1Dataset」 mentioned?

**Comment by kongds** [comment]
Thanks for reading our paper,

The "frequency" in Figure 1 is not use  the datasets in 5.1 (these datasets is too small). And we use much large corpus from wikipedia and openwebtext.
