### ISSUE TITLE
中英文的文本匹配效果堪忧呀。。。

### ISSUE THREAD

**Issue by shiwl0329** [kongds/Prompt-BERT#14]
![image](https://user-images.githubusercontent.com/13725297/197927855-4091f9cb-0b08-4542-8953-056b7538c972.png)
![image](https://user-images.githubusercontent.com/13725297/197927901-2372af87-5e45-44fa-9d04-5da4028891ca.png)

**Comment by shiwl0329** [comment]
另外我使用了sbert模型的效果对比如下：
![image](https://user-images.githubusercontent.com/13725297/197931756-7c3d7b35-6d4e-49ea-8f7e-edd25a6c06dc.png)

**Comment by kongds** [comment]
你好

应该在输入的句子中加入模板，并用[MASK] token的输出作为句子的embedding。具体内容，麻烦参考code以及paper

另外我们提供的模型目前只有英语的版本

**Comment by shiwl0329** [comment]
> 中加入

哦哦，明白了，不能直接使用transformer方式加载呀？ 另外中文版有预期不，想了解下~

**Comment by kongds** [comment]
需要修改对应的输入以及输出，具体代码请参考https://github.com/kongds/Prompt-BERT/blob/cea835f5c9b7e76fe363e5991bfad6877112ee82/evaluation.py#L186-L339

关于中文版，可能需要设计对应的中文模板。

**Comment by shiwl0329** [comment]
再请教下：是只需要单独设计中文模板还是说需要重新训练一个中文模型呢~

**Comment by kongds** [comment]
应该需要设计中文模板并重新训练

**Comment by shiwl0329** [comment]
明白了，谢谢

**Comment by kongds** [comment]
没事
