### ISSUE TITLE
A little question about the training

### ISSUE THREAD

**Issue by ilingen** [kongds/Prompt-BERT#15]
Hi, thank u for your excellent work. Please forgive me for asking a simple question.
These days, I am training a unsup-bert model. I set random _seed=0_ and  get a standard result with avg score _78.54_, which is same as the paper reported (_78.54±0.15_), both the results are lower than your provided model (78.87). 
So I wonder if you have updated the training strategy or provide the best model for us.

**Comment by kongds** [comment]
Thank you for your interest in our work.

We provide our best checkpoint from 10 random runs for unsupervised settings .  And we also report the best and worst performance of 10 random runs in paper Section 6.2.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/19282154/198183570-d13841b9-01dd-4069-b0fb-9da1ef0ec98e.png">

**Comment by ilingen** [comment]
Thanks for your reply. I am going to close the issue.
