### ISSUE TITLE
关于损失函数去除模板噪音

### ISSUE THREAD

**Issue by santiagolxs** [kongds/Prompt-BERT#17]
您好，我是一名初学者，但是看源代码的时候甚至找不到损失函数的定义，看论文对于去模板降噪也有点疑惑..请问下作者能贴一下论文里面的损失函数定义或者举一个更详细降噪的例子吗，感谢。

**Comment by kongds** [comment]
感谢关注我们的工作

首先并不是损失函数去除模板噪音，是去除句子表征中的模板噪音，然后通过这些句子表征计算损失。
简单来说就是在句子表征中减去“去掉句子token只使用template token 并保留他们相同位置编码的输入得到的表征”

相关的讨论请看  https://github.com/kongds/Prompt-BERT/issues/11 https://github.com/kongds/Prompt-BERT/issues/13

**Comment by santiagolxs** [comment]
十分感谢！
