### ISSUE TITLE
Any advice for the Chinese version?

### ISSUE THREAD

**Issue by shuopwang** [kongds/Prompt-BERT#18]
Hi, I'm trying to adopt Prompt-Bert into the public Chinese dataset.

using prompt like following:
*cls*下面这句话\"*sent_0*\"对应的语义是*mask*。*sep+*

The spearman score is much worse than the rare SimCSE.

Is there any advice for the Chinese prompts?

**Comment by kongds** [comment]
你可以先看看加入的中文模板在验证集中是否对于没有微调的BERT有帮助（相比与cls）
