### ISSUE TITLE
unsupervised contrastive learning

### ISSUE THREAD

**Issue by serotoninpm** [kongds/Prompt-BERT#19]
I understand that the concept of contrastive learning represents closer to each other and farther away.
When learning unsuperviced contrastive learning, do you use the template to bring the closest closer, but does it include the concept of further away?

**Comment by kongds** [comment]
Following previous works, we also include the concept of further away in the denominator (where i not equal to j) of the following equation
<img width="298" alt="image" src="https://user-images.githubusercontent.com/19282154/208927427-466653f6-e577-49da-8297-bdbc09b92d83.png">

**Comment by serotoninpm** [comment]
Thank you for your kind reply. Contrastive learning is an unfamiliar field to me, so I think I asked a basic question
