### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by cwszz** [kongds/Prompt-BERT#2]
Hello, I download the "unsup-bert" model, and evaluate it. I only get 77.80 on avg.
Can you add an evaluate procedure in readme or a bash file ?

**Comment by kongds** [comment]
Thanks for your advice, the evaluate procedure is already in `run.sh`.  And I will add more clear procedure in readme.
For "unsup-bert" model, it is 
```bash
TEMPLATE="*cls*_This_sentence_of_\"*sent_0*\"_means*mask*.*sep+*"
eargs=(--mask_embedding_sentence \
        --mask_embedding_sentence_template $TEMPLATE )
CUDA_VISIBLE_DEVICES=0 python evaluation.py \
    --model_name_or_path   $CHECKPOINT \
    --pooler avg\
    --mode test\
    ${eargs[@]}

```

**Comment by kongds** [comment]
Hello, I added evaluate procedure in https://github.com/kongds/Prompt-BERT/commit/3970171787228cba053c01d1fc4b8d0c6ea602d3 .

**Comment by cwszz** [comment]
Thanks for your bash. I got the correct result.

**Comment by sudarshanregmi** [comment]
Thanks for the code. I installed the given requirements. Was SEED=0 used for experiments shown in the Readme? Cause with that value of SEED, I'm not able to replicate the result. Results from retraining unsup-bert model:- 
![image](https://user-images.githubusercontent.com/19612493/152681132-b9155891-7fea-41d1-a5f2-8985b6a98b34.png)
