### ISSUE TITLE
how do i learn scratch

### ISSUE THREAD

**Issue by serotoninpm** [kongds/Prompt-BERT#20]
About ./run.sh bert-optiprompt or ./run.sh sup-roberta
How do i learn from scratch, readme is bash evaluation only.
After downloading the model via sh [unsup-bert|unsup-roberta|sup-berta], I can running ./run.sh sup-roberta. 
I'd appreciate it if you could give me a hint. I'm fascinated by your thesis.

**Comment by kongds** [comment]
for evaluating downloaded models, you should use `bash eval_only.sh [unsup-bert|unsup-roberta|sup-bert|sup-roberta]`. the commands are following:
https://github.com/kongds/Prompt-BERT/blob/cea835f5c9b7e76fe363e5991bfad6877112ee82/eval_only.sh#L48-L86

If you want to train models, you can find settings in `run.sh`. Here is settings about `unsup-bert`
https://github.com/kongds/Prompt-BERT/blob/cea835f5c9b7e76fe363e5991bfad6877112ee82/run.sh#L91-L108

which will be used in 
https://github.com/kongds/Prompt-BERT/blob/cea835f5c9b7e76fe363e5991bfad6877112ee82/run.sh#L150-L168

**Comment by serotoninpm** [comment]
if i start ./run.sh bert-optiprompt
i met this error, how can i solve this problem
<img width="1281" alt="스크린샷 2022-12-22 오후 2 00 47" src="https://user-images.githubusercontent.com/52595365/209060795-b5d806ba-30b0-4b77-863a-940e763f966a.png">
<img width="1268" alt="스크린샷 2022-12-22 오후 2 01 05" src="https://user-images.githubusercontent.com/52595365/209060798-b64df3a1-6889-482a-9226-7c6cec0319df.png">

**Comment by kongds** [comment]
Please make sure your environment is installed correctly

which can been installed from 
`pip install -r requirements.txt`

**Comment by serotoninpm** [comment]
Even though you ran pip install -r requirement.txt. What is your Python version? I did it in an environment of 3.9.

**Comment by kongds** [comment]
How about `pip install dill==0.3.5.1`?

**Comment by serotoninpm** [comment]
if i install pip install dill==0.3.5.1
<img width="515" alt="스크린샷 2022-12-22 오후 2 31 37" src="https://user-images.githubusercontent.com/52595365/209064099-ccdb171f-7f09-4d21-9683-e7cdfc54fd2d.png">

i met above error

i resolved this error: pip install dill==0.3.4

thanks for you kind reply!!
