### ISSUE TITLE
Relationships between anisotropy and removing biased tokens

### ISSUE THREAD

**Issue by kimwongyuda** [kongds/Prompt-BERT#21]
First of all, thanks for your inspiring paper.

When I read the introduction part of your paper (I haven't read all yet), I wondered one thing.

In the paper, removing biased tokens shows improvements.
However, it doesn't really have any relationships with anisotropy?

I guess tokens which appear frequently in one sentence, have high probabilities that such tokens appear in other sentences.
So, I think removing such tokens makes sentence embeddings distinguished each other.
And finally, I expect it makes sentence embeddings have different directions and be isotropic.

My opinion can be wrong !
I am just curious of your opinion.

Thank you.

**Comment by kongds** [comment]
Thanks for for your interest in our work. 

Removing biased tokens will influence the anisotropy in sentence embedding.  However, its effect is small compared to the anisotropy of using the last layer. For example, here is the results of bert-base-uncased
<img width="536" alt="image" src="https://user-images.githubusercontent.com/19282154/210046089-ff1d90cd-f9c9-4caa-9cbf-86387cc475b7.png">
Removing bias tokens in bert-base-ucased will decrease anisotropy (calculate according to Eq.1 ) from 82.5 to 78.19. But compare to `Last layer`, which only has 48.74 anisotropy.

In appendix A.2, we also try eliminating bias by pertaining three language models. By eliminating from pretraining, the debiased static token embeddings also achieve better spearman correlation(Table 12).

**Comment by kimwongyuda** [comment]
Thank you for your specific reply!
