### ISSUE TITLE
More details about the results of unfine-tuned version.

### ISSUE THREAD

**Issue by YWMditto** [kongds/Prompt-BERT#22]
Hello, first congratualations on your great work.

I want to ask the details about the performance of the unfine-tuned prompt bert using manual prompt, cause I use "The sentence of "[X]" means [MASK]." only get an result of avg 59 on sts.

Did you use template denoising also on unfine-tuned version?

**Comment by kongds** [comment]
Thank you

We don't use template denoising in unfine-tuned version. There seems something wrong in your implementation. 

You can reproduce the unfine-tuned result with `./run.sh bert-prompt`(avg 67.85 on sts). The detail implementation can been found in batcher function:
https://github.com/kongds/Prompt-BERT/blob/b79fbe8a14b2852df63e729e0688e88efabb018c/evaluation.py#L186

**Comment by YWMditto** [comment]
Ok, I have figured out what is the key to get that result.
Using "The sentence : "[X]" means [MASK]." raises the result from 59 to 62.
And adding an '.' at the end of each sentence raises 62 to 67.
Thanks for your reply, I will shut down this issue.
Good luck!
