### ISSUE TITLE
Fine Tune on bert base uncase

### ISSUE THREAD

**Issue by SophieLiao0001** [kongds/Prompt-BERT#24]
Hi, there,

I am trying to use your script to train unsup prompt bert, however, I keep getting "CUDA OUT OF MOMORY" Error even though I set the batch size to be 32(I want to use a 12 GB GPU). 
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/90343439/215393626-8f3da7c6-1dba-4604-9de8-0e5eccc1f4f0.png">

I am not familiar with your script, but I do have some experiences with SimCSE. Usually, if I specify GPU with os.environ["CUDA_DEVICE_ORDER"] in train.py, it will work. Not sure how this can be done with your script.
Any help would be appreciated.

**Comment by kongds** [comment]
Hello
We use 256 batch size for unsup bert, which requires around 16GB GPU memory.

You can modify batch size here for unsup bert (like 128 which can fit in 12GB GPU)
https://github.com/kongds/Prompt-BERT/blob/093e343ab89c40fc120a1de9dacc6d7ec4e6292e/run.sh#L94

**Comment by SophieLiao0001** [comment]
Hi, there,

Thank you. The above problem is a server issue. It's working now. In your paper, you mentioned that you have implemented a manual search and have used a greedy search to find templates, ''Then we greedily search for templates following
the relationship tokens and prefix tokens''.  Which part of your code reflects this greedy search process?

**Comment by kongds** [comment]
The template is searched by manual. We first search relationship tokens and use the best relationship tokens to search prefix tokens. like bellow:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/19282154/215644408-1224beff-6a5b-4550-a5a2-ba31f7212152.png">

The results of template in dev set are from following command:
```bash
TEMPLAE="*cls*_This_sentence_of_\"*sent_0*\"_means*mask*.*sep+*" # template to eval
CUDA_VISIBLE_DEVICES=0 python evaluation.py \
        --model_name_or_path  bert-base-uncased\
        --pooler avg\
        --mode dev\
        --mask_embedding_sentence \
        --mask_embedding_sentence_template  $TEMPLATE

```
