### ISSUE TITLE
p_mbv 是什么意思？

### ISSUE THREAD

**Issue by XuJianzhi** [kongds/Prompt-BERT#25]
感谢大佬们的作品。

https://github.com/kongds/Prompt-BERT/blob/main/prompt_bert/models.py#L397

p_mbv 是什么意思？
self.p_mbv = torch.nn.Parameter(torch.zeros(10))  ， 为何是10 ？

**Comment by kongds** [comment]
感谢关注我们的工作

`p_mbv`是在微调prompt template embedding时template的权重，对应论文中表5的Prompt based BERT (manual&OptiPrompt)。

设置成这个只是为了方便模型保存以及读取该参数，`p_mbv`的值具体定义在这块

https://github.com/kongds/Prompt-BERT/blob/093e343ab89c40fc120a1de9dacc6d7ec4e6292e/train.py#L802-L824
