### ISSUE TITLE
加载中文模型有问题

### ISSUE THREAD

**Issue by XuJianzhi** [kongds/Prompt-BERT#26]
大佬们好。
我改成本地加载 hfl-chinese-roberta-wwm-ext https://huggingface.co/hfl/chinese-roberta-wwm-ext 。
显示参数加载都有问题
![1675768993889](https://user-images.githubusercontent.com/30584453/217231871-8a7291cd-9973-446b-8c03-e4e750529a56.png)
应该改哪里，谢谢！

**Comment by XuJianzhi** [comment]
是不是得改 https://github.com/kongds/Prompt-BERT/blob/main/prompt_bert/models.py#L452 ？
改成 AutoModel.from_pretrained("路径/hfl-chinese-roberta-wwm-ext") ?

**Comment by kongds** [comment]
这个不是我们repo的问题

应该是你的权重和模型的class 没有对应上。
另外模型的首页上已经有说明了，需要用BERT来加载
<img width="898" alt="image" src="https://user-images.githubusercontent.com/19282154/218313649-4fc7a89c-e75f-4f7e-8575-7e131f6db28d.png">
