### ISSUE TITLE
Consult the meanings of some parameter 

### ISSUE THREAD

**Issue by Gyyyym** [kongds/Prompt-BERT#28]
What are the meanings of these parameters? Can you explain them in detail？Thank you very much！
1.mask_embedding_sentence_delta
2.mask_embedding_sentence_org_mlp
3.mask_embedding_sentence_delta_freeze
4.mask_embedding_sentence_delta_no_position

**Comment by kongds** [comment]
Hello, these flags refers to following meanings:
1.`mask_embedding_sentence_delta` refers to the template denoising in our paper.
2.`mask_embedding_sentence_org_mlp`  uses `BertPredictionHeadTransform` as sentence embeddings mlp.
3.`mask_embedding_sentence_delta_freeze` freeze the grads from template denoising.
4.`mask_embedding_sentence_delta_no_position` not use same position ids with sentence embeddings in denoising.
