### ISSUE TITLE
RuntimeError: cosine_similarity requires both inputs to have the same sizes, but x1 has [128, 1, 768] and x2 has [1, 128, 768]

### ISSUE THREAD

**Issue by zhaijianyang** [kongds/Prompt-BERT#31]
![image](https://github.com/kongds/Prompt-BERT/assets/56312792/2a1d21ea-0e1c-40a4-a819-ee6d439410a8)

**Comment by kongds** [comment]
We use `Similarity` to get cosine_similarity which can calculate cosine similarity  between [128, 1, 768] and  [1, 128, 768], and return matrix with shape [128, 128]
https://github.com/kongds/Prompt-BERT/blob/24c9c20f1b3957f7de833ed2479d29488ad6a791/prompt_bert/models.py#L38-L49
