### ISSUE TITLE
OSError: Can't load config for 'unsup-roberta'

### ISSUE THREAD

**Issue by Joyzzzhe** [kongds/Prompt-BERT#33]
It's my honor to read your article!
However, when I run the command `bash eval_only.sh unsup-roberta`, it raised error:

```
OSError: Can't load config for 'unsup-roberta'. Make sure that:

- 'unsup-roberta' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'unsup-roberta' is the correct path to a directory containing a config.json file
```
and
`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/unsup-roberta/resolve/main/config.json`

I don't know how to solve, so I came to ask for your help. I would really appreciate it!

**Comment by kongds** [comment]
Thanks for your interesting to our paper. 

We have uploaded our models to HuggingFace hub in https://github.com/kongds/Prompt-BERT/commit/690ba6ef3a1d954c24d9a992ff8e339816866a05. Please pull the change first, and run the command again.

**Comment by Joyzzzhe** [comment]
Thank you for your patient and timely solution!
