### ISSUE TITLE
请问关于监督的promptbert的结果问题

### ISSUE THREAD

**Issue by taofennanhai** [kongds/Prompt-BERT#34]
我通过huggingface下载了监督的promptbert模型。
然后我发现在测试结果和论文中的效果展现不一致，语义相似度任务上差别较大，迁移任务上和论文一致，请问是什么原因
![1703070326542](https://github.com/kongds/Prompt-BERT/assets/44886954/6e000687-852e-494d-8606-851e0dd61c00)

命令行
```
python evaluation.py --model_name_or_path result/sup-PromptBERT \
                                 --pooler avg \
                                 --mode test \ 
                                 --task_set full \
                                 --mask_embedding_sentence \
                                 --mask_embedding_sentence_template "*cls*_This_sentence_:_'_*sent_0*_'_means*mask*.*sep+*"
```

在V100卡上面测试的

**Comment by kongds** [comment]
请使用eval_only.sh中的flag，也可以直接用bash eval_only.sh sup-bert复现结果
https://github.com/kongds/Prompt-BERT/blob/690ba6ef3a1d954c24d9a992ff8e339816866a05/eval_only.sh#L37-L46

**Comment by taofennanhai** [comment]
我改用上述命令后确实语义相似度确实达到论文中的效果，但貌似在这个背景下的迁移任务效果下降了，是不是可以理解为在论文展示两个任务上的是两套不同的模型设置？
![1703082728326](https://github.com/kongds/Prompt-BERT/assets/44886954/0d2846f7-58e9-49c3-aff7-782b5684801e)

**Comment by kongds** [comment]
在 https://github.com/kongds/Prompt-BERT/issues/34#issue-2050331379 中的命令应该是不对的，用了roberta的prompt

论文中transfer的结果是用的如下命令（用的和STS一样的prompt 但是没有加 `--mask_embedding_sentence_org_mlp`和`--mask_embedding_sentence_delta`）
```bash
python evaluation.py \
        --model_name_or_path  $MODEL\
        --pooler avg\                                   
        --mode test\                                   
        --mask_embedding_sentence \                                                                 
        --task_set  transfer \                                                                      
        --mask_embedding_sentence_template "*cls*_This_sentence_of_\"*sent_0*\"_means*mask*.*sep+*"  
```
具体的讨论可以参考 https://github.com/kongds/Prompt-BERT/issues/23#issuecomment-1382653303 https://github.com/kongds/Prompt-BERT/issues/23#issuecomment-1382661328

**Comment by taofennanhai** [comment]
感谢你的解答
