### ISSUE TITLE
understanding the denoise step

### ISSUE THREAD

**Issue by riyajatar37003** [kongds/Prompt-BERT#35]
Thanks for the paper.
I am going through the paper , am having doubt on this point.

To reduce the influence of the template itself on the sentence representation, we propose a novel way to denoise the template information. Given the sentence xi, we first calculate the corresponding sentence embeddings hi with a template. Then we calculate the template bias ˆ hi by directly feeding BERT with the template and the same template position ids. For example, if the xi has 5 tokens, then the position ids of template tokens after the [X] will be added by 5 to make sure the position ids of template are same. Finally, we can directly use the hi − ˆ hi as the denoised sentence representation. For the template denoising, more details can be found in Discussion.

here when u say sentence embeddings <hi> , does it mean representation corresponding to [MASK] token or what?
when u say directly feed to bert from which token ur consideriong the emedding ?

can u explain with one example how ur doing token positon ids adjuestement

thanks

**Comment by kongds** [comment]
Hi,

For the first question, the representations correspond to the [MASK] token. For the second question, we still use the [MASK] token as the sentence embedding.

For example, if we use template like `T1 <s1> T2 [MASK]`, where  `<s1>` is sentence and `T1 , T2`  are template tokens,  we feed BERT with `T1:pos_id0` `T2:pos_id(1+len(s1))` `[MASK]:pos_id(2+len(s1))` to represent bias of `s1`. (pos_id is the position id, len(s1) is the length of `s1` tokens)

You can also refer to this issue: https://github.com/kongds/Prompt-BERT/issues/11#issue-1285200973.

**Comment by riyajatar37003** [comment]
thanks for reply its clear now.
