### ISSUE TITLE
Calculation of anisotropy

### ISSUE THREAD

**Issue by beckybai** [kongds/Prompt-BERT#4]
Hi, thanks for the code sharing. May I ask if the anisotropy calculation step is included in this repo. If not, could you please share more details about this part? e.g. dataset used (train/dev/test).

Thanks again.

**Comment by kongds** [comment]
Hi, I add the anisotorpy caculation in https://github.com/kongds/Prompt-BERT/commit/8c0cb4cd62e5c3037cd9a6935f95b7353365cb55 .
For example, 
```sh
EXP=bert-base-uncased | bert-base-uncased-static-embedding | bert-base-uncased-static-embedding-remove-baises 
./run.sh calc-anisotropy-${EXP}
```
For other pretrained models, just replace `bert-base-uncased` with other models.
