### ISSUE TITLE
How to generate sentence embedding on customized data?

### ISSUE THREAD

**Issue by Vincentwei1021** [kongds/Prompt-BERT#5]
Hi Thanks for releasing the code. I would like to know how to generate sentence embedding on customized data? 

Thanks

**Comment by kongds** [comment]
https://github.com/kongds/Prompt-BERT/blob/8c0cb4cd62e5c3037cd9a6935f95b7353365cb55/evaluation.py#L342-L351
Hi,  you can follow the above lines in `evaluation.py` to dump custom data.

**Comment by Vincentwei1021** [comment]
> https://github.com/kongds/Prompt-BERT/blob/8c0cb4cd62e5c3037cd9a6935f95b7353365cb55/evaluation.py#L342-L351
> 
> 
> Hi, you can follow the above lines in `evaluation.py` to dump custom data.

@kongds Thanks for the advice. While running the above code, I encountered the following error:
![image](https://user-images.githubusercontent.com/18239147/157000675-a547c86b-9028-47ec-b712-fa681d057498.png)
I print the related tensors; 
print(batch['attention_mask'].sum(-1), template_len, blen)
print(delta.shape, blen.shape)
tensor([ 45,  16,  61,  33,  23,  35,  30,  97,  42,  81,  35,  50,  34,  32,
         61,  46,  96,  23,  40,  29,  40,  62,  38,  44,  35,  23,  44,  31,
         39,  36,  29,  55,  45,  44,  39,  59,  35,  64,  40,  55,  40,  40,
         41,  25, 142,  21,  46,  42,  31,  40,  35,  87,  44,  48,  42,  33,
         87,  61]) 10 tensor([ 35,   6,  51,  23,  13,  25,  20,  87,  32,  71,  25,  40,  24,  22,
         51,  36,  86,  13,  30,  19,  30,  52,  28,  34,  25,  13,  34,  21,
         29,  26,  19,  45,  35,  34,  29,  49,  25,  54,  30,  45,  30,  30,
         31,  15, 132,  11,  36,  32,  21,  30,  25,  77,  34,  38,  32,  23,
         77,  51])
torch.Size([128, 768]) torch.Size([58])
Clearly 132 exceeds the index boundary of 128, but it's not clear for me why this happened.

**Comment by kongds** [comment]
Hi, the length of `input_ids` exceeds 128.
Just change `batcher(None, batch)` to `batcher(None, batch, max_length=128)` in evaluation.py:349 and evaluation.py:351.
