### ISSUE TITLE
Standard deviation

### ISSUE THREAD

**Issue by qfkkwgd** [kongds/Prompt-BERT#6]
Hi,

Thanks for your brilliant work! 

I have a question about the results. I noticed that only unsupervised models are reported with standard deviation. Why supervised models are not reported with the standard deviation?

Also, would you mind to share about the random seeds that you used?

Thanks a lot!

**Comment by kongds** [comment]
Hello, 
Thank you.

According to our experiment, the deviation in supervised models is too small to ignore.

And we just use the default seed "42" in huggingface.
