### ISSUE TITLE
how this "length" should be understood

### ISSUE THREAD

**Issue by xiaolang01** [kongds/Prompt-BERT#7]
![image](https://user-images.githubusercontent.com/44439592/161428654-f40a424b-a764-4f8e-954e-877dfa92dfc0.png)I would like to ask how this "length" should be understood

**Comment by kongds** [comment]
Hello, length is the size of cached prompt delta.
For example, if length is 50, we cache 50  prompt deltas with different position ids to match input texts with length from 1 to 50.
