### ISSUE TITLE
question on fine-tune

### ISSUE THREAD

**Issue by llllly26** [kongds/Prompt-BERT#8]
Hi,
I met some questions that when I want to fine-tuned with the command  `./run.sh unsup-bert 0` ,there is an error that `OSError: Can't load config for 'result/unsup-bert_s0'.` I want to know that if I need to download the model under the **Results on STS Tasks**  title? and I am confused that Shouldn't these models be obtained after this command is executed?  What should I put in the `result` directory？
thanks!

**Comment by kongds** [comment]
Hello
This command will train unsup-bert with seed 0 and evaluate it on STS. And don’t need put anything in result directory.

It seems something wrong with training scripts. Can you show me the error before OSError?

**Comment by llllly26** [comment]
thanks for your reply! 
when I run `./run.sh unsup-bert $SEED` and there are some errors.as shown here,
![image](https://user-images.githubusercontent.com/38215077/161664311-4bb65429-19cf-400c-bd4a-dd639554d3f9.png)
![image](https://user-images.githubusercontent.com/38215077/161664546-f37febc8-ccd9-4e9b-87e8-c38494b54cb2.png)
and when i run the command `./run.sh sup-bert` ,It also shows that there is nothing in the `result` directory
could you please help me? 
thank you!

**Comment by kongds** [comment]
Hello
It seems your sever can’t reach githubuserconnect.com which is used for data loading in https://github.com/kongds/Prompt-BERT/blob/8c0cb4cd62e5c3037cd9a6935f95b7353365cb55/train.py#L533

You can follow things like [this](https://blog.csdn.net/qq_20849045/article/details/117462846) to solve ConnectionError.

**Comment by llllly26** [comment]
thank you! 
and I found another method that updating the version of dataset1.2.1 to 1.3.0.
