### ISSUE TITLE
Why adding periods during evaluation? 

### ISSUE THREAD

**Issue by qfkkwgd** [kongds/Prompt-BERT#9]
I noticed that you add periods during evaluation (in eval.py). I am not so sure if this operation is valid because I didn't find the same operation in SimCSE's evaluation code. I notice results under certain settings drop if I remove this operation.

**Comment by kongds** [comment]
Hello,  periods are part of template, which help the representation of sentence.

For  unfined-tuned  BERT `bert-base-uncased`,  adding periods can improve the spearman from  67.67 to 70.34 on dev set in SICK.
